<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AFG'],
            ['name' => 'Albania', 'code' => 'ALB'],
            ['name' => 'Algeria', 'code' => 'DZA'],
            ['name' => 'American Samoa', 'code' => 'ASM'],
            ['name' => 'Andorra', 'code' => 'AND'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Anguilla', 'code' => 'AIA'],
            ['name' => 'Antarctica', 'code' => 'ATA'],
            ['name' => 'Antigua and Barbuda', 'code' => 'ATG'],
            ['name' => 'Argentina', 'code' => 'ARG'],
            ['name' => 'Armenia', 'code' => 'ARM'],
            ['name' => 'Aruba', 'code' => 'ABW'],
            ['name' => 'Australia', 'code' => 'AUS'],
            ['name' => 'Austria', 'code' => 'AUT'],
            ['name' => 'Azerbaijan', 'code' => 'AZE'],
            ['name' => 'Bahamas', 'code' => 'BHS'],
            ['name' => 'Bahrain', 'code' => 'BHR'],
            ['name' => 'Bangladesh', 'code' => 'BGD'],
            ['name' => 'Barbados', 'code' => 'BRB'],
            ['name' => 'Belarus', 'code' => 'BLR'],
            ['name' => 'Belgium', 'code' => 'BEL'],
            ['name' => 'Belize', 'code' => 'BLZ'],
            ['name' => 'Benin', 'code' => 'BEN'],
            ['name' => 'Bermuda', 'code' => 'BMU'],
            ['name' => 'Bhutan', 'code' => 'BTN'],
            ['name' => 'Bolivia, Plurinational State of', 'code' => 'BOL'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BES'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH'],
            ['name' => 'Botswana', 'code' => 'BWA'],
            ['name' => 'Bouvet Island', 'code' => 'BVT'],
            ['name' => 'Brazil', 'code' => 'BRA'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IOT'],
            ['name' => 'Brunei Darussalam', 'code' => 'BRN'],
            ['name' => 'Bulgaria', 'code' => 'BGR'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Burundi', 'code' => 'BDI'],
            ['name' => 'Cambodia', 'code' => 'KHM'],
            ['name' => 'Cameroon', 'code' => 'CMR'],
            ['name' => 'Canada', 'code' => 'CAN'],
            ['name' => 'Cayman Islands', 'code' => 'CYM'],
            ['name' => 'Central African Republic', 'code' => 'CAF'],
            ['name' => 'Chad', 'code' => 'TCD'],
            ['name' => 'Chile', 'code' => 'CHL'],
            ['name' => 'China', 'code' => 'CHN'],
            ['name' => 'Christmas Island', 'code' => 'CXR'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CCK'],
            ['name' => 'Colombia', 'code' => 'COL'],
            ['name' => 'Comoros', 'code' => 'COM'],
            ['name' => 'Congo', 'code' => 'COG'],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'COD'],
            ['name' => 'Cook Islands', 'code' => 'COK'],
            ['name' => 'Costa Rica', 'code' => 'CRI'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CIV'],
            ['name' => 'Croatia', 'code' => 'HRV'],
            ['name' => 'Cuba', 'code' => 'CUB'],
            ['name' => 'Curaçao', 'code' => 'CUW'],
            ['name' => 'Cyprus', 'code' => 'CYP'],
            ['name' => 'Denmark', 'code' => 'DNK'],
            ['name' => 'Djibouti', 'code' => 'DJI'],
            ['name' => 'Dominica', 'code' => 'DMA'],
            ['name' => 'Dominican Republic', 'code' => 'DOM'],
            ['name' => 'Ecuador', 'code' => 'ECU'],
            ['name' => 'Egypt', 'code' => 'EGY'],
            ['name' => 'El Salvador', 'code' => 'SLV'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
            ['name' => 'Eritrea', 'code' => 'ERI'],
            ['name' => 'Estonia', 'code' => 'EST'],
            ['name' => 'Ethiopia', 'code' => 'ETH'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FLK'],
            ['name' => 'Faroe Islands', 'code' => 'FRO'],
            ['name' => 'Fiji', 'code' => 'FJI'],
            ['name' => 'Finland', 'code' => 'FIN'],
            ['name' => 'France', 'code' => 'FRA'],
            ['name' => 'French Guiana', 'code' => 'GUF'],
            ['name' => 'French Polynesia', 'code' => 'PYF'],
            ['name' => 'French Southern Territories', 'code' => 'ATF'],
            ['name' => 'Gabon', 'code' => 'GAB'],
            ['name' => 'Gambia', 'code' => 'GMB'],
            ['name' => 'Georgia', 'code' => 'GEO'],
            ['name' => 'Germany', 'code' => 'DEU'],
            ['name' => 'Ghana', 'code' => 'GHA'],
            ['name' => 'Gibraltar', 'code' => 'GIB'],
            ['name' => 'Greece', 'code' => 'GRC'],
            ['name' => 'Greenland', 'code' => 'GRL'],
            ['name' => 'Grenada', 'code' => 'GRD'],
            ['name' => 'Guadeloupe', 'code' => 'GLP'],
            ['name' => 'Guam', 'code' => 'GUM'],
            ['name' => 'Guatemala', 'code' => 'GTM'],
            ['name' => 'Guernsey', 'code' => 'GGY'],
            ['name' => 'Guinea', 'code' => 'GIN'],
            ['name' => 'Guinea-Bissau', 'code' => 'GNB'],
            ['name' => 'Guyana', 'code' => 'GUY'],
            ['name' => 'Haiti', 'code' => 'HTI'],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'HMD'],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VAT'],
            ['name' => 'Honduras', 'code' => 'HND'],
            ['name' => 'Hong Kong', 'code' => 'HKG'],
            ['name' => 'Hungary', 'code' => 'HUN'],
            ['name' => 'Iceland', 'code' => 'ISL'],
            ['name' => 'India', 'code' => 'IND'],
            ['name' => 'Indonesia', 'code' => 'IDN'],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IRN'],
            ['name' => 'Iraq', 'code' => 'IRQ'],
            ['name' => 'Ireland', 'code' => 'IRL'],
            ['name' => 'Isle of Man', 'code' => 'IMN'],
            ['name' => 'Israel', 'code' => 'ISR'],
            ['name' => 'Italy', 'code' => 'ITA'],
            ['name' => 'Jamaica', 'code' => 'JAM'],
            ['name' => 'Japan', 'code' => 'JPN'],
            ['name' => 'Jersey', 'code' => 'JEY'],
            ['name' => 'Jordan', 'code' => 'JOR'],
            ['name' => 'Kazakhstan', 'code' => 'KAZ'],
            ['name' => 'Kenya', 'code' => 'KEN'],
            ['name' => 'Kiribati', 'code' => 'KIR'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'PRK'],
            ['name' => 'Korea, Republic of', 'code' => 'KOR'],
            ['name' => 'Kuwait', 'code' => 'KWT'],
            ['name' => 'Kyrgyzstan', 'code' => 'KGZ'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LAO'],
            ['name' => 'Latvia', 'code' => 'LVA'],
            ['name' => 'Lebanon', 'code' => 'LBN'],
            ['name' => 'Lesotho', 'code' => 'LSO'],
            ['name' => 'Liberia', 'code' => 'LBR'],
            ['name' => 'Libya', 'code' => 'LBY'],
            ['name' => 'Liechtenstein', 'code' => 'LIE'],
            ['name' => 'Lithuania', 'code' => 'LTU'],
            ['name' => 'Luxembourg', 'code' => 'LUX'],
            ['name' => 'Macao', 'code' => 'MAC'],
            ['name' => 'Madagascar', 'code' => 'MDG'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Malaysia', 'code' => 'MYS'],
            ['name' => 'Maldives', 'code' => 'MDV'],
            ['name' => 'Mali', 'code' => 'MLI'],
            ['name' => 'Malta', 'code' => 'MLT'],
            ['name' => 'Marshall Islands', 'code' => 'MHL'],
            ['name' => 'Martinique', 'code' => 'MTQ'],
            ['name' => 'Mauritania', 'code' => 'MRT'],
            ['name' => 'Mauritius', 'code' => 'MUS'],
            ['name' => 'Mayotte', 'code' => 'MYT'],
            ['name' => 'Mexico', 'code' => 'MEX'],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FSM'],
            ['name' => 'Moldova, Republic of', 'code' => 'MDA'],
            ['name' => 'Monaco', 'code' => 'MCO'],
            ['name' => 'Mongolia', 'code' => 'MNG'],
            ['name' => 'Montenegro', 'code' => 'MNE'],
            ['name' => 'Montserrat', 'code' => 'MSR'],
            ['name' => 'Morocco', 'code' => 'MAR'],
            ['name' => 'Mozambique', 'code' => 'MOZ'],
            ['name' => 'Myanmar', 'code' => 'MMR'],
            ['name' => 'Namibia', 'code' => 'NAM'],
            ['name' => 'Nauru', 'code' => 'NRU'],
            ['name' => 'Nepal', 'code' => 'NPL'],
            ['name' => 'Netherlands', 'code' => 'NLD'],
            ['name' => 'New Caledonia', 'code' => 'NCL'],
            ['name' => 'New Zealand', 'code' => 'NZL'],
            ['name' => 'Nicaragua', 'code' => 'NIC'],
            ['name' => 'Niger', 'code' => 'NER'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'Niue', 'code' => 'NIU'],
            ['name' => 'Norfolk Island', 'code' => 'NFK'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MNP'],
            ['name' => 'Norway', 'code' => 'NOR'],
            ['name' => 'Oman', 'code' => 'OMN'],
            ['name' => 'Pakistan', 'code' => 'PAK'],
            ['name' => 'Palau', 'code' => 'PLW'],
            ['name' => 'Palestinian Territory, Occupied', 'code' => 'PSE'],
            ['name' => 'Panama', 'code' => 'PAN'],
            ['name' => 'Papua New Guinea', 'code' => 'PNG'],
            ['name' => 'Paraguay', 'code' => 'PRY'],
            ['name' => 'Peru', 'code' => 'PER'],
            ['name' => 'Philippines', 'code' => 'PHL'],
            ['name' => 'Pitcairn', 'code' => 'PCN'],
            ['name' => 'Poland', 'code' => 'POL'],
            ['name' => 'Portugal', 'code' => 'PRT'],
            ['name' => 'Puerto Rico', 'code' => 'PRI'],
            ['name' => 'Qatar', 'code' => 'QAT'],
            ['name' => 'Romania', 'code' => 'ROU'],
            ['name' => 'Russian Federation', 'code' => 'RUS'],
            ['name' => 'Rwanda', 'code' => 'RWA'],
            ['name' => 'Saint Barthélemy', 'code' => 'BLM'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SHN'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KNA'],
            ['name' => 'Saint Lucia', 'code' => 'LCA'],
            ['name' => 'Saint Martin (French part)', 'code' => 'MAF'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'SPM'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VCT'],
            ['name' => 'Samoa', 'code' => 'WSM'],
            ['name' => 'San Marino', 'code' => 'SMR'],
            ['name' => 'Sao Tome and Principe', 'code' => 'STP'],
            ['name' => 'Saudi Arabia', 'code' => 'SAU'],
            ['name' => 'Senegal', 'code' => 'SEN'],
            ['name' => 'Serbia', 'code' => 'SRB'],
            ['name' => 'Seychelles', 'code' => 'SYC'],
            ['name' => 'Sierra Leone', 'code' => 'SLE'],
            ['name' => 'Singapore', 'code' => 'SGP'],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SXM'],
            ['name' => 'Slovakia', 'code' => 'SVK'],
            ['name' => 'Slovenia', 'code' => 'SVN'],
            ['name' => 'Solomon Islands', 'code' => 'SLB'],
            ['name' => 'Somalia', 'code' => 'SOM'],
            ['name' => 'South Africa', 'code' => 'ZAF'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'SGS'],
            ['name' => 'South Sudan', 'code' => 'SSD'],
            ['name' => 'Spain', 'code' => 'ESP'],
            ['name' => 'Sri Lanka', 'code' => 'LKA'],
            ['name' => 'Sudan', 'code' => 'SDN'],
            ['name' => 'Suriname', 'code' => 'SUR'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJM'],
            ['name' => 'Sweden', 'code' => 'SWE'],
            ['name' => 'Switzerland', 'code' => 'CHE'],
            ['name' => 'Syrian Arab Republic', 'code' => 'SYR'],
            ['name' => 'Taiwan, Province of China', 'code' => 'TWN'],
            ['name' => 'Tajikistan', 'code' => 'TJK'],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZA'],
            ['name' => 'Thailand', 'code' => 'THA'],
            ['name' => 'Timor-Leste', 'code' => 'TLS'],
            ['name' => 'Togo', 'code' => 'TGO'],
            ['name' => 'Tokelau', 'code' => 'TKL'],
            ['name' => 'Tonga', 'code' => 'TON'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TTO'],
            ['name' => 'Tunisia', 'code' => 'TUN'],
            ['name' => 'Turkey', 'code' => 'TUR'],
            ['name' => 'Turkmenistan', 'code' => 'TKM'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TCA'],
            ['name' => 'Tuvalu', 'code' => 'TUV'],
            ['name' => 'Uganda', 'code' => 'UGA'],
            ['name' => 'Ukraine', 'code' => 'UKR'],
            ['name' => 'United Arab Emirates', 'code' => 'ARE'],
            ['name' => 'United Kingdom', 'code' => 'GBR'],
            ['name' => 'United States', 'code' => 'USA'],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UMI'],
            ['name' => 'Uruguay', 'code' => 'URY'],
            ['name' => 'Uzbekistan', 'code' => 'UZB'],
            ['name' => 'Vanuatu', 'code' => 'VUT'],
            ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VEN'],
            ['name' => 'Viet Nam', 'code' => 'VNM'],
            ['name' => 'Virgin Islands, British', 'code' => 'VGB'],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VIR'],
            ['name' => 'Wallis and Futuna', 'code' => 'WLF'],
            ['name' => 'Western Sahara', 'code' => 'ESH'],
            ['name' => 'Yemen', 'code' => 'YEM'],
            ['name' => 'Zambia', 'code' => 'ZMB'],
            ['name' => 'Zimbabwe', 'code' => 'ZWE'],




            ['name' => 'Afghanistan', 'code' => 'AF'],
            ['name' => 'Åland Islands', 'code' => 'AX'],
            ['name' => 'Albania', 'code' => 'AL'],
            ['name' => 'Algeria', 'code' => 'DZ'],
            ['name' => 'American Samoa', 'code' => 'AS'],
            ['name' => 'Andorra', 'code' => 'AD'],
            ['name' => 'Angola', 'code' => 'AO'],
            ['name' => 'Anguilla', 'code' => 'AI'],
            ['name' => 'Antarctica', 'code' => 'AQ'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG'],
            ['name' => 'Argentina', 'code' => 'AR'],
            ['name' => 'Armenia', 'code' => 'AM'],
            ['name' => 'Aruba', 'code' => 'AW'],
            ['name' => 'Australia', 'code' => 'AU'],
            ['name' => 'Austria', 'code' => 'AT'],
            ['name' => 'Azerbaijan', 'code' => 'AZ'],
            ['name' => 'Bahamas', 'code' => 'BS'],
            ['name' => 'Bahrain', 'code' => 'BH'],
            ['name' => 'Bangladesh', 'code' => 'BD'],
            ['name' => 'Barbados', 'code' => 'BB'],
            ['name' => 'Belarus', 'code' => 'BY'],
            ['name' => 'Belgium', 'code' => 'BE'],
            ['name' => 'Belize', 'code' => 'BZ'],
            ['name' => 'Benin', 'code' => 'BJ'],
            ['name' => 'Bermuda', 'code' => 'BM'],
            ['name' => 'Bhutan', 'code' => 'BT'],
            ['name' => 'Bolivia, Plurinational State of', 'code' => 'BO'],
            ['name' => 'Bonaire, Sint Eustatius and Saba', 'code' => 'BQ'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA'],
            ['name' => 'Botswana', 'code' => 'BW'],
            ['name' => 'Bouvet Island', 'code' => 'BV'],
            ['name' => 'Brazil', 'code' => 'BR'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO'],
            ['name' => 'Brunei Darussalam', 'code' => 'BN'],
            ['name' => 'Bulgaria', 'code' => 'BG'],
            ['name' => 'Burkina Faso', 'code' => 'BF'],
            ['name' => 'Burundi', 'code' => 'BI'],
            ['name' => 'Cambodia', 'code' => 'KH'],
            ['name' => 'Cameroon', 'code' => 'CM'],
            ['name' => 'Canada', 'code' => 'CA'],
            ['name' => 'Cape Verde', 'code' => 'CV'],
            ['name' => 'Cayman Islands', 'code' => 'KY'],
            ['name' => 'Central African Republic', 'code' => 'CF'],
            ['name' => 'Chad', 'code' => 'TD'],
            ['name' => 'Chile', 'code' => 'CL'],
            ['name' => 'China', 'code' => 'CN'],
            ['name' => 'Christmas Island', 'code' => 'CX'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC'],
            ['name' => 'Colombia', 'code' => 'CO'],
            ['name' => 'Comoros', 'code' => 'KM'],
            ['name' => 'Congo', 'code' => 'CG'],
            ['name' => 'Congo, the Democratic Republic of the', 'code' => 'CD'],
            ['name' => 'Cook Islands', 'code' => 'CK'],
            ['name' => 'Costa Rica', 'code' => 'CR'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI'],
            ['name' => 'Croatia', 'code' => 'HR'],
            ['name' => 'Cuba', 'code' => 'CU'],
            ['name' => 'Curaçao', 'code' => 'CW'],
            ['name' => 'Cyprus', 'code' => 'CY'],
            ['name' => 'Czech Republic', 'code' => 'CZ'],
            ['name' => 'Denmark', 'code' => 'DK'],
            ['name' => 'Djibouti', 'code' => 'DJ'],
            ['name' => 'Dominica', 'code' => 'DM'],
            ['name' => 'Dominican Republic', 'code' => 'DO'],
            ['name' => 'Ecuador', 'code' => 'EC'],
            ['name' => 'Egypt', 'code' => 'EG'],
            ['name' => 'El Salvador', 'code' => 'SV'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ'],
            ['name' => 'Eritrea', 'code' => 'ER'],
            ['name' => 'Estonia', 'code' => 'EE'],
            ['name' => 'Ethiopia', 'code' => 'ET'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK'],
            ['name' => 'Faroe Islands', 'code' => 'FO'],
            ['name' => 'Fiji', 'code' => 'FJ'],
            ['name' => 'Finland', 'code' => 'FI'],
            ['name' => 'France', 'code' => 'FR'],
            ['name' => 'French Guiana', 'code' => 'GF'],
            ['name' => 'French Polynesia', 'code' => 'PF'],
            ['name' => 'French Southern Territories', 'code' => 'TF'],
            ['name' => 'Gabon', 'code' => 'GA'],
            ['name' => 'Gambia', 'code' => 'GM'],
            ['name' => 'Georgia', 'code' => 'GE'],
            ['name' => 'Germany', 'code' => 'DE'],
            ['name' => 'Ghana', 'code' => 'GH'],
            ['name' => 'Gibraltar', 'code' => 'GI'],
            ['name' => 'Greece', 'code' => 'GR'],
            ['name' => 'Greenland', 'code' => 'GL'],
            ['name' => 'Grenada', 'code' => 'GD'],
            ['name' => 'Guadeloupe', 'code' => 'GP'],
            ['name' => 'Guam', 'code' => 'GU'],
            ['name' => 'Guatemala', 'code' => 'GT'],
            ['name' => 'Guernsey', 'code' => 'GG'],
            ['name' => 'Guinea', 'code' => 'GN'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW'],
            ['name' => 'Guyana', 'code' => 'GY'],
            ['name' => 'Haiti', 'code' => 'HT'],
            ['name' => 'Heard Island and McDonald Islands', 'code' => 'HM'],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA'],
            ['name' => 'Honduras', 'code' => 'HN'],
            ['name' => 'Hong Kong', 'code' => 'HK'],
            ['name' => 'Hungary', 'code' => 'HU'],
            ['name' => 'Iceland', 'code' => 'IS'],
            ['name' => 'India', 'code' => 'IN'],
            ['name' => 'Indonesia', 'code' => 'ID'],
            ['name' => 'Iran, Islamic Republic of', 'code' => 'IR'],
            ['name' => 'Iraq', 'code' => 'IQ'],
            ['name' => 'Ireland', 'code' => 'IE'],
            ['name' => 'Isle of Man', 'code' => 'IM'],
            ['name' => 'Israel', 'code' => 'IL'],
            ['name' => 'Italy', 'code' => 'IT'],
            ['name' => 'Jamaica', 'code' => 'JM'],
            ['name' => 'Japan', 'code' => 'JP'],
            ['name' => 'Jersey', 'code' => 'JE'],
            ['name' => 'Jordan', 'code' => 'JO'],
            ['name' => 'Kazakhstan', 'code' => 'KZ'],
            ['name' => 'Kenya', 'code' => 'KE'],
            ['name' => 'Kiribati', 'code' => 'KI'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP'],
            ['name' => 'Korea, Republic of', 'code' => 'KR'],
            ['name' => 'Kuwait', 'code' => 'KW'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA'],
            ['name' => 'Latvia', 'code' => 'LV'],
            ['name' => 'Lebanon', 'code' => 'LB'],
            ['name' => 'Lesotho', 'code' => 'LS'],
            ['name' => 'Liberia', 'code' => 'LR'],
            ['name' => 'Libya', 'code' => 'LY'],
            ['name' => 'Liechtenstein', 'code' => 'LI'],
            ['name' => 'Lithuania', 'code' => 'LT'],
            ['name' => 'Luxembourg', 'code' => 'LU'],
            ['name' => 'Macao', 'code' => 'MO'],
            ['name' => 'Macedonia, the former Yugoslav Republic of', 'code' => 'MK'],
            ['name' => 'Madagascar', 'code' => 'MG'],
            ['name' => 'Malawi', 'code' => 'MW'],
            ['name' => 'Malaysia', 'code' => 'MY'],
            ['name' => 'Maldives', 'code' => 'MV'],
            ['name' => 'Mali', 'code' => 'ML'],
            ['name' => 'Malta', 'code' => 'MT'],
            ['name' => 'Marshall Islands', 'code' => 'MH'],
            ['name' => 'Martinique', 'code' => 'MQ'],
            ['name' => 'Mauritania', 'code' => 'MR'],
            ['name' => 'Mauritius', 'code' => 'MU'],
            ['name' => 'Mayotte', 'code' => 'YT'],
            ['name' => 'Mexico', 'code' => 'MX'],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FM'],
            ['name' => 'Moldova, Republic of', 'code' => 'MD'],
            ['name' => 'Monaco', 'code' => 'MC'],
            ['name' => 'Mongolia', 'code' => 'MN'],
            ['name' => 'Montenegro', 'code' => 'ME'],
            ['name' => 'Montserrat', 'code' => 'MS'],
            ['name' => 'Morocco', 'code' => 'MA'],
            ['name' => 'Mozambique', 'code' => 'MZ'],
            ['name' => 'Myanmar', 'code' => 'MM'],
            ['name' => 'Namibia', 'code' => 'NA'],
            ['name' => 'Nauru', 'code' => 'NR'],
            ['name' => 'Nepal', 'code' => 'NP'],
            ['name' => 'Netherlands', 'code' => 'NL'],
            ['name' => 'New Caledonia', 'code' => 'NC'],
            ['name' => 'New Zealand', 'code' => 'NZ'],
            ['name' => 'Nicaragua', 'code' => 'NI'],
            ['name' => 'Niger', 'code' => 'NE'],
            ['name' => 'Nigeria', 'code' => 'NG'],
            ['name' => 'Niue', 'code' => 'NU'],
            ['name' => 'Norfolk Island', 'code' => 'NF'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP'],
            ['name' => 'Norway', 'code' => 'NO'],
            ['name' => 'Oman', 'code' => 'OM'],
            ['name' => 'Pakistan', 'code' => 'PK'],
            ['name' => 'Palau', 'code' => 'PW'],
            ['name' => 'Palestinian Territory, Occupied', 'code' => 'PS'],
            ['name' => 'Panama', 'code' => 'PA'],
            ['name' => 'Papua New Guinea', 'code' => 'PG'],
            ['name' => 'Paraguay', 'code' => 'PY'],
            ['name' => 'Peru', 'code' => 'PE'],
            ['name' => 'Philippines', 'code' => 'PH'],
            ['name' => 'Pitcairn', 'code' => 'PN'],
            ['name' => 'Poland', 'code' => 'PL'],
            ['name' => 'Portugal', 'code' => 'PT'],
            ['name' => 'Puerto Rico', 'code' => 'PR'],
            ['name' => 'Qatar', 'code' => 'QA'],
            ['name' => 'Réunion', 'code' => 'RE'],
            ['name' => 'Romania', 'code' => 'RO'],
            ['name' => 'Russian Federation', 'code' => 'RU'],
            ['name' => 'Rwanda', 'code' => 'RW'],
            ['name' => 'Saint Barthélemy', 'code' => 'BL'],
            ['name' => 'Saint Helena, Ascension and Tristan da Cunha', 'code' => 'SH'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN'],
            ['name' => 'Saint Lucia', 'code' => 'LC'],
            ['name' => 'Saint Martin (French part)', 'code' => 'MF'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC'],
            ['name' => 'Samoa', 'code' => 'WS'],
            ['name' => 'San Marino', 'code' => 'SM'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST'],
            ['name' => 'Saudi Arabia', 'code' => 'SA'],
            ['name' => 'Senegal', 'code' => 'SN'],
            ['name' => 'Serbia', 'code' => 'RS'],
            ['name' => 'Seychelles', 'code' => 'SC'],
            ['name' => 'Sierra Leone', 'code' => 'SL'],
            ['name' => 'Singapore', 'code' => 'SG'],
            ['name' => 'Sint Maarten (Dutch part)', 'code' => 'SX'],
            ['name' => 'Slovakia', 'code' => 'SK'],
            ['name' => 'Slovenia', 'code' => 'SI'],
            ['name' => 'Solomon Islands', 'code' => 'SB'],
            ['name' => 'Somalia', 'code' => 'SO'],
            ['name' => 'South Africa', 'code' => 'ZA'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS'],
            ['name' => 'South Sudan', 'code' => 'SS'],
            ['name' => 'Spain', 'code' => 'ES'],
            ['name' => 'Sri Lanka', 'code' => 'LK'],
            ['name' => 'Sudan', 'code' => 'SD'],
            ['name' => 'Suriname', 'code' => 'SR'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ'],
            ['name' => 'Swaziland', 'code' => 'SZ'],
            ['name' => 'Sweden', 'code' => 'SE'],
            ['name' => 'Switzerland', 'code' => 'CH'],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY'],
            ['name' => 'Taiwan, Province of China', 'code' => 'TW'],
            ['name' => 'Tajikistan', 'code' => 'TJ'],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ'],
            ['name' => 'Thailand', 'code' => 'TH'],
            ['name' => 'Timor-Leste', 'code' => 'TL'],
            ['name' => 'Togo', 'code' => 'TG'],
            ['name' => 'Tokelau', 'code' => 'TK'],
            ['name' => 'Tonga', 'code' => 'TO'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT'],
            ['name' => 'Tunisia', 'code' => 'TN'],
            ['name' => 'Turkey', 'code' => 'TR'],
            ['name' => 'Turkmenistan', 'code' => 'TM'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC'],
            ['name' => 'Tuvalu', 'code' => 'TV'],
            ['name' => 'Uganda', 'code' => 'UG'],
            ['name' => 'Ukraine', 'code' => 'UA'],
            ['name' => 'United Arab Emirates', 'code' => 'AE'],
            ['name' => 'United Kingdom', 'code' => 'GB'],
            ['name' => 'United States', 'code' => 'US'],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM'],
            ['name' => 'Uruguay', 'code' => 'UY'],
            ['name' => 'Uzbekistan', 'code' => 'UZ'],
            ['name' => 'Vanuatu', 'code' => 'VU'],
            ['name' => 'Venezuela, Bolivarian Republic of', 'code' => 'VE'],
            ['name' => 'Viet Nam', 'code' => 'VN'],
            ['name' => 'Virgin Islands, British', 'code' => 'VG'],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI'],
            ['name' => 'Wallis and Futuna', 'code' => 'WF'],
            ['name' => 'Western Sahara', 'code' => 'EH'],
            ['name' => 'Yemen', 'code' => 'YE'],
            ['name' => 'Zambia', 'code' => 'ZM'],
            ['name' => 'Zimbabwe', 'code' => 'ZW']
        ];

        DB::table('counties')->insert($countries);
    }
}
