<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class booking_tour extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
        'tourID',
        'bookingId',
        'invoice_number',
        'country',
        'star',
        'tot_room',
        'currency',
        'date_from',
        'date_to',
        'lead_pass_name',
        'lead_pass_email',
        'lead_pass_country',
        'lead_pass_mobile',
        'default_act1',
        'default_act2',
        'default_act3',
        'default_act4',
        'default_act5',
        'add_act1',
        'add_act2',
        'add_act3',
        'add_act4',
        'add_act5',
        'adult1',
        'adult2',
        'adult3',
        'adult4',
        'adult5',
        'adult6',
        'adult7',
        'adult8',
        'adult9',
        'adult10',
        'adult11',
        'adult12',
        'adult13',
        'adult14',
        'adult15',
        'adult16',
        'adult17',
        'adult18',
        'child1',
        'child2',
        'child3',
        'child4',
        'child5',
        'child6',
        'child7',
        'child8',
        'child9',
        'child10',
        'child11',
        'child12',
        'child13',
        'child14',
        'isTour',
        'offer',
        'public',
        'baseFare',
        'offerFare',
        'publicFare',
        'agent_public_price',
        'agent_offer_price',
        'agent_commission',
        'agent_tds',
        'agent_invoice_price',
        'agent_net_receivable',
        'cancel_status',
        'cancel_date',
        'updatedOn',
        'addedOn',
        'addedBy',
    ];
}
